ardop:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  shoulder_1_joint_position_controller:
    type: position_controllers/JointPositionController
    joint: shoulder_1_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}

  upper_1_joint_position_controller:
    type: position_controllers/JointPositionController
    joint: upper_1_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}

  lower_1_joint_position_controller:
    type: position_controllers/JointPositionController
    joint: lower_1_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}

  lower_2_joint_position_controller:
    type: position_controllers/JointPositionController
    joint: lower_2_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}

  ee_pitch_joint_position_controller:
    type: position_controllers/JointPositionController
    joint: ee_pitch_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}

  ee_roll_joint_position_controller:
    type: position_controllers/JointPositionController
    joint: ee_roll_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}

  end_effector_joint_position_controller:
    type: position_controllers/JointPositionController
    joint: end_effector_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}

  wheel_front_left_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: wheel_front_left_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}

  wheel_front_right_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: wheel_front_right_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}

  wheel_back_left_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: wheel_back_left_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}

  wheel_back_right_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: wheel_back_right_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
